### ISSUE TITLE
Release 0.2.2 with JRuby support

### ISSUE THREAD

**Issue by headius** [ruby/io-wait#17]
Hello from JRuby!

We have been testing JRuby master (9.4) on its own and with Rails 7 for the past couple weeks using 0.2.2-pre1 and the JRuby extension appears to be functioning properly.

I am requesting that we do a formal release, so that JRuby 9.4 and Rails 7 users do not have to request --pre gems.

**Comment by hsbt** [comment]
I released 0.2.3 with https://github.com/ruby/io-wait/commit/f59d1d12e04cc4e3afd3833f8b5c90cae43123eb (It should be use 0.2.2, I missed that)
